"""Campaign workspace scaffolding service."""

import re
from dataclasses import asdict
from pathlib import Path

import yaml

from core.project import Project
from models.campaign import CampaignManifest

_SLUG_PATTERN = re.compile(r"[^a-z0-9]+")
_HASHTAG_PATTERN = re.compile(r"[^A-Za-z0-9]")

CAMPAIGN_DIRECTORIES = (
    "captions",
    "radio",
    "press",
    "playlist",
    "analytics",
    "schedule",
    "assets/artwork",
    "assets/videos",
    "assets/photos",
)

DEFAULT_FILES = {
    "captions/instagram.md": "# Instagram Captions\n",
    "captions/facebook.md": "# Facebook Captions\n",
    "captions/tiktok.md": "# TikTok Captions\n",
    "captions/x.md": "# X Captions\n",
    "radio/stations.csv": "station,contact,status,notes\n",
    "radio/followups.md": "# Radio Follow-ups\n",
    "radio/interviews.md": "# Radio Interviews\n",
    "playlist/spotify.md": "# Spotify Playlist Outreach\n",
    "playlist/apple.md": "# Apple Music Playlist Outreach\n",
    "press/blogs.md": "# Blog Outreach\n",
    "press/press-release.md": "# Press Release\n",
    "analytics/weekly.md": "# Weekly Analytics\n",
    "analytics/monthly.md": "# Monthly Analytics\n",
    "schedule/content-calendar.md": "# Content Calendar\n",
}


def slugify(value: str) -> str:
    """Convert a campaign name into a filesystem-safe slug."""
    slug = _SLUG_PATTERN.sub("-", value.strip().lower()).strip("-")
    if not slug:
        raise ValueError("Campaign name must contain at least one letter or number.")
    return slug


def hashtag(value: str) -> str:
    """Convert a value into a simple hashtag token."""
    return _HASHTAG_PATTERN.sub("", value)


class CampaignService:
    """Creates campaign workspaces inside a CreativeOS project."""

    def __init__(self, project: Project) -> None:
        self.project = project

    def create(self, name: str, *, artist: str | None = None) -> Path:
        """Create and return a new campaign workspace path."""
        campaign_name = name.strip()
        campaign_path = self.project.campaigns_path / slugify(campaign_name)

        if campaign_path.exists():
            raise FileExistsError(f"Campaign already exists: {campaign_path.name}")

        campaign_path.mkdir(parents=True)

        for directory in CAMPAIGN_DIRECTORIES:
            (campaign_path / directory).mkdir(parents=True, exist_ok=True)

        campaign_artist = artist.strip() if artist else self.project.artist

        hashtags = [
            tag
            for tag in (
                hashtag(self.project.genre),
                hashtag(campaign_artist),
            )
            if tag
        ]

        manifest = CampaignManifest(
            name=campaign_name,
            artist=campaign_artist,
            hashtags=hashtags,
        )

        self._write_manifest(campaign_path, manifest)
        self._write_readme(campaign_path, manifest)

        for relative_path, content in DEFAULT_FILES.items():
            (campaign_path / relative_path).write_text(
                content,
                encoding="utf-8",
            )

        return campaign_path

    @staticmethod
    def _write_manifest(path: Path, manifest: CampaignManifest) -> None:
        data = asdict(manifest)
        (path / "campaign.yaml").write_text(
            yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )

    @staticmethod
    def _write_readme(path: Path, manifest: CampaignManifest) -> None:
        content = f"""# {manifest.name}

Campaign workspace for **{manifest.artist}**.

## Objectives

- Grow streaming activity
- Reach radio stations
- Pitch playlists
- Coordinate creator marketing
- Track campaign analytics

Generated by CreativeOS.
"""

        (path / "README.md").write_text(content, encoding="utf-8")
